In [5]:
import numpy as np
b=np.array([1,2,3,4,5,6,7,8,9])
slice1=b[3:7]
print(slice1)

[4 5 6 7]


In [8]:
slice2=b[::2]
print(slice2)

[1 4 7]


In [11]:
rev=b[::-3]
print(rev)

[9 6 3]


In [25]:

c=np.array([[1,2,3],[9,8,7],[1,3,5]])
subarray=c[0:3,0:1]
print(subarray)


[[1]
 [9]
 [1]]


In [27]:
col=c[:,0]
print(col)

[1 9 1]


In [34]:
row=c[2,:]
print(row)

[1 3 5]


In [40]:
print(c[0,0])
print(c[2,2])

1
5


In [42]:
b=np.array([20,30,10,40,60])
print(b[-3])

10


In [43]:
print(b[1:4])

[30 10 40]


In [44]:
print(b[b>25])

[30 40 60]


In [47]:
d=np.array([[1,2],[3,4]])
e=np.array([[5,6],[7,8]])
result=np.hstack((d,e))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [48]:
result=np.vstack((d,e))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [49]:
res=np.dstack((d,e))
print(res)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [59]:
b=np.array([1,2,3,4,5,6])
result=np.split(b,2)
print(result)

[array([1, 2, 3]), array([4, 5, 6])]


In [60]:
b=np.array([1,2,3,4,5])
result=np.array_split(b,3)
print(result)

[array([1, 2]), array([3, 4]), array([5])]
