In [34]:
import numpy as np
a=np.array([10,20,30,40,50])
b=np.array([[10,20,30,40,50],[60,70,80,90,99]])


In [4]:
print("One dimensional array ",a)

One dimensional array  [10 20 30 40 50]


In [5]:
print("Two dimensional array ",b)


Two dimensional array  [[10 20 30 40 50]
 [60 70 80 90 99]]


In [35]:
c=np.zeros((3,4))


In [7]:
print("Array with all Zeros \n",c)


Array with all Zeros 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
d=np.random.random((3,4))


In [9]:
print("Array with random numbers \n",d)


Array with random numbers 
 [[0.64089644 0.69237622 0.27023371 0.15903444]
 [0.34118581 0.26501762 0.72153965 0.31283318]
 [0.19504891 0.11238298 0.33869405 0.06035692]]


In [10]:
e=np.arange(0,10,1)


In [11]:
print("Array with range value \n",e)


Array with range value 
 [0 1 2 3 4 5 6 7 8 9]


In [12]:
f=np.array([[1,2,3,0],[7,5,9,8],[4,8,6,2]])
g=f.reshape((4,3))

In [13]:
print("Original array : \n",f)
print("\n Reshaped array : \n",g)

Original array : 
 [[1 2 3 0]
 [7 5 9 8]
 [4 8 6 2]]

 Reshaped array : 
 [[1 2 3]
 [0 7 5]
 [9 8 4]
 [8 6 2]]


In [14]:
h=np.zeros((5,3))
i=np.random.random((5,3))
j=np.array([[1,2,3,0,4],[7,5,9,6,8],[5,4,8,6,2]])
k=j.reshape((5,3))
l=np.arange(0,100,10)



In [15]:
print("Array with all Zeros \n",h)
print("Array with random numbers \n",i)
print("Original array : \n",k)
print("\n Reshaped array : \n",j)
print("Array with range value \n",l)




Array with all Zeros 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array with random numbers 
 [[0.50406155 0.50338567 0.47821684]
 [0.87326253 0.706837   0.44627241]
 [0.72707829 0.07118001 0.62300944]
 [0.16461853 0.4582434  0.59220428]
 [0.01675236 0.62174058 0.0379303 ]]
Original array : 
 [[1 2 3]
 [0 4 7]
 [5 9 6]
 [8 5 4]
 [8 6 2]]

 Reshaped array : 
 [[1 2 3 0 4]
 [7 5 9 6 8]
 [5 4 8 6 2]]
Array with range value 
 [ 0 10 20 30 40 50 60 70 80 90]


In [16]:
flat=j.flatten()
print("Flattend array :",flat)

Flattend array : [1 2 3 0 4 7 5 9 6 8 5 4 8 6 2]


In [17]:
print("No.of dimensions: ",j.ndim)

No.of dimensions:  2


In [18]:
print("Shape of the array: ",j.shape)

Shape of the array:  (3, 5)


In [19]:
print("\n Array element type:",j.dtype)


 Array element type: int32


In [27]:
ba=j.astype('f')
print("\n count array element:\n",ba)
print("Converted array: ",ba.dtype)


 count array element:
 [[1. 2. 3. 0. 4.]
 [7. 5. 9. 6. 8.]
 [5. 4. 8. 6. 2.]]
Converted array:  float32


In [36]:
size=len(j) 
print("\n size of array:\n",j.size)


 size of array:
 15
